# Generated by Django 2.0.3 on 2018-07-09 20:41

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_platform', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'ANDROID'), ('WIN PHONE', 'WINDOWS PHONE')], default=None, max_length=10)),
                ('os_version', models.CharField(default=None, max_length=10)),
                ('device_gpu', models.CharField(blank=True, default=None, help_text='Only required if Platform is "Android".', max_length=20)),
                ('device_name', models.CharField(default=None, max_length=20)),
                ('mac_address', macaddress.fields.MACAddressField(blank=True, integer=False, max_length=17)),
            ],
        ),
    ]
