# Generated by Django 2.0.3 on 2018-07-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'ANDROID'), ('WIN PHONE', 'WINDOWS PHONE')], default=None, max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
