# Generated by Django 2.0.3 on 2018-07-10 16:26

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('devices_farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='company_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_color',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='imei_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='memory_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='screen_diagonal',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='screen_resolution',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sd_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='sim_card',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_gpu',
            field=models.CharField(blank=True, default=None, help_text='Only required if Platform is "Android".', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=macaddress.fields.MACAddressField(blank=True, default='', integer=False, max_length=17, null=True),
        ),
    ]
