# Generated by Django 2.0.3 on 2018-07-12 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices_farm', '0002_auto_20180710_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Create a new platform.', max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': (['platform', 'type', 'device_name'],), 'verbose_name': 'devices'},
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_gpu',
            new_name='GPU',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='imei_number',
            new_name='imei',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_platform',
        ),
        migrations.AddField(
            model_name='device',
            name='characteristics_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('p', 'Phone'), ('t', 'Tablet')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='device',
            name='memory_size',
            field=models.IntegerField(help_text='Size in GB.'),
        ),
        migrations.AddField(
            model_name='device',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices_farm.Platform'),
        ),
    ]
