# Generated by Django 2.0.3 on 2018-07-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices_farm', '0003_auto_20180712_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['platform', 'type', 'device_name']},
        ),
    ]
